name: build and push github actions container image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PULL_STAGES_LOG: pull-stages-output.log
      BUILD_LOG: build-output.log
      IMAGE_NAME: renegare/github-action-container
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_PAT}}
      - uses: whoan/docker-build-with-cache-action@v5
        id: build
        with:
          username: "${{ secrets.DOCKER_USER }}"
          password: "${{ secrets.DOCKER_PASS }}"
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: latest,${{ github.sha }}
          pull_image_and_stages: true
          push_image_and_stages: true
          push_image_tag: true
      - name: Summary
        run: |
          echo "Image Pushed: ${{steps.build.outputs.FULL_IMAGE_NAME}}"
          echo "List of images: https://hub.docker.com/r/renegare/github-action-container/tags?page=1&ordering=last_updated"
      # - name: Slack Notification
      #   uses: rtCamp/action-slack-notify@v2.0.1
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_TITLE: Renegare Github Actions Container Build Complete ✅
      #     SLACK_MESSAGE: Image has been built and pushed to https://hub.docker.com/r/renegare/github-action-container/tags?page=1&ordering=last_updated
